### ISSUE TITLE
Workshop #4 - Elm and JS InterOp

### ISSUE THREAD

**Issue by madsflensted** [elm-singapore/meetups#1]
Details

  * [x] Event: Workshop
  * [x] Date: Wedensday April 26
  * [x] Hosts: @madsflensted and @olejrosendahl
  * [x] Venue sponsor: Hackerspace.sg
  * [x] Food/drinks sponsor: 
  
Organizers tasks:
  * [x] Announce on Meetup.com

**Comment by madsflensted** [comment]
So @olejrosendahl said we could do this event at Hackerspace.sg, and there is room next week. So currently setting that up. 
If any of you, @mpizenberg @peterhoeg @shishkin @hhandoko @yeongsheng-tan @tjjjwxzq @mgajda or anyone else, would like a say on the day - then now is the time.

**Comment by mpizenberg** [comment]
Great, hum I'm busy on Tuesday, otherwise every day is fine

**Comment by tjjjwxzq** [comment]
25 and 26 preferred :)

**Comment by hhandoko** [comment]
Hackerspace.SG sounds good 👍  I'm OK any day!

**Comment by peterhoeg** [comment]
I'm out Tuesday as well, but other days are good.

**Comment by madsflensted** [comment]
Ok then I suggest we go for Wedensday

**Comment by madsflensted** [comment]
@peterhoeg where you still up for sponsoring some pizzas?

**Comment by peterhoeg** [comment]
👍

**Comment by madsflensted** [comment]
Ok will talk to @olejrosendahl about the scheduling. The draft announcement is here: https://www.meetup.com/Elm-Singapore/events/239373268/

**Comment by peterhoeg** [comment]
The draft announcement is only available to organizers.

**Comment by madsflensted** [comment]
Thank you everyone for participating - and especially @olerosendahl for hosting at Hackerspace.sg and @peterhoeg for sponsoring the pizzas!
