### ISSUE TITLE
Elm Workshop #5

### ISSUE THREAD

**Issue by madsflensted** [elm-singapore/meetups#3]
Details

  * [ ] Event: Workshop
  * [ ] Date:  December
  * [ ] Hosts:
  * [ ] Venue sponsor:
  * [ ] Food/drinks sponsor:
  
Organizers tasks:
  * [ ] Announce on Meetup.com

**Comment by madsflensted** [comment]
@peterhoeg will you be able to put me in contact with Trade-Gecko to see if they could host us in December?
I am thinking we would do hands-on, and maybe split into  beginner group, and more advanced group, e.g. focussing on Ports.

**Comment by peterhoeg** [comment]
Done. You probably want to update the date.
