### ISSUE TITLE
Elm Talks #2

### ISSUE THREAD

**Issue by madsflensted** [elm-singapore/meetups#4]
Details

  * [x] Event: Elm Talks
  * [x] Date: Monday November 6.
  * [x] Organizer(s): @madsflensted
  * [x] Venue sponsor: [ThoughtWorks Singapore](https://goo.gl/maps/JPejMZr19Cs)
  * [x] Food/drinks sponsor: ThoughtWorks Singapore
  
Organizers tasks:
  * [x] Announce on Meetup.com
  
Talks:
  * "Designing elm packages, steps and caveats"  by @mpizenberg

**Comment by madsflensted** [comment]
If you have something Elm that you would like to present just leave a comment here. We will schedule the event once we have a 2-3 speakers.

**Comment by madsflensted** [comment]
Had a twitter-chat with Benjamin Tan Wei Hao, https://twitter.com/bentanweihao/status/897247612205645824, and he was positive about presenting something.

Question is @mpizenberg is there any chance you would talk about something too in September? Something from your list, or just how you use Elm in your PhD project?

**Comment by mpizenberg** [comment]
@madsflensted, I might but not entirely positive. Don't hesitate to ping me later this month

**Comment by madsflensted** [comment]
No worries - just checking

**Comment by mpizenberg** [comment]
Now that I think of it, what I might like to present would be something about creating packages in elm. "Designing elm packages, steps and caveats" or similar. It would probably be a 40 min format though, not 20 min.

**Comment by peterhoeg** [comment]
I would REALLY like to hear that talk!

**Comment by mpizenberg** [comment]
oh no, so much pressure now ^^

**Comment by mpizenberg** [comment]
So, I've been thinking a little about the content of the presentation. I came up with a plan like this :

1. The current package ecosystem
  a. The packages repository (website)
  b. Installing / using / removing a package
  c. `elm-package.json`
  d. Semantic versionning
2. Some drawbacks to be aware of
  a. Github hosting (deleted repo)
  b. Per project dependencies installations (even `Core`!)
  c. Elm only -> very few packages
  d. No private repository mechanism
3. Designing steps
  a. When not to create a package
  b. When to create a package
  c. My package creation checklist
    (documentation, tests, examples, license, readme, elm-format, opaque types, simple defaults)
4. Actual shipping
  a. First package release
  b. Update package steps
5. What the future holds

What do you guys think? anything important missing?

**Comment by madsflensted** [comment]
It sounds like you are covering a lot.
But it all sounds interesting

**Comment by madsflensted** [comment]
@benjamintanweihao and @mpizenberg shall we try to target last week of September? 25/9 - 28/9.

**Comment by mpizenberg** [comment]
It's good for me, do you know if ThoughtWorks is ok to host us again?

**Comment by benjamintanweihao** [comment]
I'm good. I'll be presenting implementing L-systems in Elm. In other words, nothing too practical :trollface:

**Comment by madsflensted** [comment]
Great looking forward to that.
I will reach out to ThoughtWorks and see if they can host us.

**Comment by madsflensted** [comment]
I haven't gotten an answer from ThoughtWorks yet - and we are starting to get a bit close to end of Sept. Maybe we should consider pushing it to beginning of Oct? Let's see what this week brings.

**Comment by benjamintanweihao** [comment]
@madsflensted I wouldn't mind October :)

**Comment by mpizenberg** [comment]
yep, fine for me too

**Comment by madsflensted** [comment]
Ok, so ThoughtWorks are free on 30/10 and 31/10.
@benjamintanweihao <https://github.com/benjamintanweihao> and @mpizenberg
<https://github.com/mpizenberg> any preferences?

**Comment by mpizenberg** [comment]
Well, I hoped it would be beginning of October. I'm leaving for 2 weeks on
the 21 of October ...

**Comment by mpizenberg** [comment]
Now I feel bad ^^ I leave singapore 2 times a year, each time being a possible meetup day :(

**Comment by madsflensted** [comment]
Yeah, you could almost think that the organizer had a hidden agenda ;-D

Don't feel bad, I just looked at my calendar and saw no real openings in
first part of October,  and Devopsdays in the next to last week, so
suggested above dates to TW.

And I completely forgot about your paper getting accepted.

So we have two options,

1 go ahead with end October. I could try to take your spot and show intro
to styles-elememts pacakage.

2 target a date in November when you are back.

I prefer 2, what about you?

**Comment by mpizenberg** [comment]
I would prefer 2 + you presenting Matthew's package :) I really like his approach and would love to hear about it.

**Comment by madsflensted** [comment]
I am having a fun using it, but a different approach it is

On Sep 20, 2017 17:56, "Matthieu Pizenberg" <notifications@github.com>
wrote:

I would prefer 2 + you presenting Matthew's package :) I really like his
approach and would love to hear about it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elm-singapore/meetups/issues/4#issuecomment-330804791>,
or mute the thread

**Comment by madsflensted** [comment]
So I am gong to ask TW about availability from 6/11 to 9/11

**Comment by madsflensted** [comment]
I have agreed with ThoughtWorks on Monday 6/11, I have updated the description.
I will announce on Meetup during Monday.

**Comment by mpizenberg** [comment]
Thanks Mads!

**Comment by madsflensted** [comment]
@mpizenberg @benjamintanweihao 9 days heads up :-)

**Comment by madsflensted** [comment]
And should we ask @hhandoko if Enigineers.sg would be up for recording the sessions?

**Comment by hhandoko** [comment]
Yup, of course @madsflensted !

**Comment by madsflensted** [comment]
Ok so Benjamin just became a father over the weekend, Congratulations! So naturally he will not be joining us.
@mpizenberg how about you, are you still up for your part?

**Comment by mpizenberg** [comment]
Hi everyone, yep I'm still up! I am currently on holidays in SF so I'm
living basically without internet except in the evening. The presentation
is not ready yet but will be :). Also I'm planning to go to the SF elm
Meetup of this Wednesday so I hope I might be able to bring some stickers
back ;)

On Oct 28, 2017 21:54, "Mads Flensted-Urech" <notifications@github.com>
wrote:

Ok so Benjamin just became a father over the weekend, Congratulations! So
naturally he will not be joining us.
@mpizenberg <https://github.com/mpizenberg> how about you, are you still up
for your part?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elm-singapore/meetups/issues/4#issuecomment-340237650>,
or mute the thread

**Comment by madsflensted** [comment]
Sounds great - hope you enjoy the trip - and are lucky with the stickers :-)

**Comment by mpizenberg** [comment]
Didn't get lucky with the stickers :( they don't have enough left. Now preparing the presentation at boarding gate ;)

**Comment by hhandoko** [comment]
Hi @madsflensted , who's your contact at TW? Want to confirm if they still hold the recording equipment there.

**Comment by madsflensted** [comment]
Sahil is.  You can reach him via Meetup.

**Comment by mpizenberg** [comment]
Hello, @madsflensted do you think we should send a reminder meetup email for tonight? people registered for long time tend to forget.

**Comment by madsflensted** [comment]
I was thinking the same but Meetup already sends these reminders.
Did you get reminder -

**Comment by madsflensted** [comment]
Did you get email about the comment I just posted on Meetup group?

**Comment by mpizenberg** [comment]
Nope none, they might come later.

**Comment by mpizenberg** [comment]
[elm_packages.pdf](https://github.com/elm-singapore/meetups/files/1445578/elm_packages.pdf)
Any typo, or horrific mistake?

**Comment by madsflensted** [comment]
Looks great, looking forward to it

On Mon, Nov 6, 2017 at 5:06 PM, Matthieu Pizenberg <notifications@github.com

**Comment by madsflensted** [comment]
Thank you all for a great event
